# Generated by Django 3.0.5 on 2020-04-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_dcn_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='DCN_number',
            new_name='dcn_number',
        ),
    ]
