# Generated by Django 3.0.5 on 2020-04-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200422_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dcn_number',
            field=models.CharField(max_length=100),
        ),
    ]
