# Generated by Django 3.0.5 on 2020-04-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contents',
        ),
        migrations.AddField(
            model_name='post',
            name='description_of_change',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
