# Generated by Django 3.0.5 on 2020-04-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200422_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='closes_dcr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('1_day', '1 Day'), ('2_day', '2 Days'), ('1_week', '1 week'), ('2_week', '2 weeks')], default='1_week', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='reason_of_change',
            field=models.TextField(default='reason_of_change'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_of_change',
            field=models.TextField(default='description_of_change'),
        ),
    ]
